schema-version = "1.15.0"

[install]
bun.pkg-path = "bun"
bun.version = "1.3.13"
infer.flake = "github:inference-gateway/cli/v0.183.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "2.1.238"
claude-code.pkg-group = "claude-code"
codex.pkg-path = "codex"
codex.version = "0.149.0"
codex.pkg-group = "codex"
go-task.pkg-path = "go-task"
go-task.version = "3.52.0"

[hook]
on-activate = '''
  task setup
'''
